replicaCount: 1

image:
  repository: us-east1-docker.pkg.dev/core-workshop/workshop-registry/insurance-frontend
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
     cert-manager.io/cluster-issuer: staging-issuer
  hosts:
    - host: REPLACE_GITHUB_ORG.staging.workshop.cb-sa.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: staging-tls
      hosts:
        - REPLACE_GITHUB_ORG.staging.workshop.cb-sa.io

backendUrl: https://example.com
fmToken: abcdefg123456789
